language: node_js

node_js:
  - node

cache: false

sudo: false

branches:
  only:
    - master

script:
  - hexo generate # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
