language: node_js
node_js:
  - node # use latest version of nodejs
cache:
  directories:
    - "node_modules" # cache the modules for faster build
branches:
  only:
    - master
before_install:
  - npm install
before_script:
  - git config --global user.name 'weyusi via Travis CI'
  - git config --global user.email 'weyusi@users.noreply.github.com'
  - sed -i'' "s~git@github.com:weyusi/hexo-testing.git~https://$GH_TOKEN:x-oauth-basic@github.com/weyusi/hexo-testing.git~" _config.yml
install:
  - hexo generate
script:
  - hexo deploy
